branches:
  only:
    - master

os: Visual Studio 2017

clone_folder: c:\projects\g2o

platform: x64
configuration: Release

build:
  project: c:\projects\g2o\build\g2o.sln 

environment:
  VCPKG_ROOT_DIR: C:\tools\vcpkg
  VCPKG_DEFAULT_TRIPLET: x64-windows

install:
  - set QTDIR=C:\Qt\5.10.0\msvc2017_64
  - set PATH=%PATH%;%QTDIR%\bin
  - C:\projects\g2o\script\install-deps-windows.bat

cache: 
  - C:\tools\vcpkg\installed -> C:\projects\g2o\script\install-deps-windows.bat
    
before_build:
  - cd C:\projects\g2o
  - mkdir build
  - cd build
  - cmake -G "Visual Studio 14 2017 Win64" -DG2O_BUILD_APPS=ON -DG2O_BUILD_EXAMPLES=ON -DVCPKG_TARGET_TRIPLET="%VCPKG_DEFAULT_TRIPLET%" -DCMAKE_TOOLCHAIN_FILE="%VCPKG_ROOT_DIR%\scripts\buildsystems\vcpkg.cmake" ..
